### ISSUE TITLE
Make thusfresh network root

### ISSUE THREAD

**Issue by josh** [thusfresh/relay-compiler-webpack-plugin#10]
👋 Hi, I work at @github and was wondering if @thusfresh and @danielholmes would be okay with making [danielholmes/relay-compiler-webpack-plugin](https://github.com/danielholmes/relay-compiler-webpack-plugin) the network root as its the maintained fork. We have some backend buttons to make this change. What will happen is that the @thusfresh repo will says its a fork of @danielholmes instead of the other way around. Let me know if you both approve and I can make it happen. Thanks!

<img width="450" alt="screen shot 2017-11-22 at 1 43 58 pm" src="https://user-images.githubusercontent.com/137/33151089-4cb670f2-cf8b-11e7-8ae3-72cc17cf8e30.png">

**Comment by danielholmes** [comment]
@josh Yes I'm okay with this

**Comment by josh** [comment]
Done.
