### ISSUE TITLE
Error is misattributed to wrong file

### ISSUE THREAD

**Issue by coleturner** [thusfresh/relay-compiler-webpack-plugin#3]
Hey!

Thank you for this fantastic plugin it is very nice to have.

While running a build, I ran across the following error message:
```
webpack_1   | ERROR in ./app/assets/stylesheets/main.scss
webpack_1   | Module build failed: Error: You supplied a GraphQL document with validation errors:
webpack_1   | Variable "$cursor" of type "ID" used in position expecting type "String".
webpack_1   | Argument "first" has invalid value count.
webpack_1   | Expected type "Int", found count.
webpack_1   |     at Object.validate (/mnt/node_modules/relay-compiler/lib/RelayValidator.js:19:17)
webpack_1   |     at convertASTDefinitions (/mnt/node_modules/relay-compiler/lib/ASTConvert.js:104:31)
webpack_1   |     at Object.convertASTDocumentsWithBase (/mnt/node_modules/relay-compiler/lib/ASTConvert.js:86:10)
webpack_1   |     at RelayFileWriter.<anonymous> (/mnt/node_modules/relay-compiler/lib/RelayFileWriter.js:93:49)
webpack_1   |     at Generator.next (<anonymous>)
webpack_1   |     at step (/mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
webpack_1   |     at /mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
webpack_1   |     at F (/mnt/node_modules/core-js/library/modules/_export.js:35:28)
webpack_1   |     at RelayFileWriter.<anonymous> (/mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
webpack_1   |     at RelayFileWriter.writeAll (/mnt/node_modules/relay-compiler/lib/RelayFileWriter.js:184:19)
webpack_1   |     at RelayCodegenRunner.<anonymous> (/mnt/node_modules/relay-compiler/lib/RelayCodegenRunner.js:172:44)
webpack_1   |     at Generator.next (<anonymous>)
webpack_1   |     at step (/mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
webpack_1   |     at /mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
webpack_1   |     at F (/mnt/node_modules/core-js/library/modules/_export.js:35:28)
webpack_1   |     at RelayCodegenRunner.<anonymous> (/mnt/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
```

The error above was misattributed to a CSS file. I'm guessing this is a limitation of Webpack but I thought I should create this issue in case there is something that can be done about it.

**Comment by tazsingh** [comment]
Hey @colepatrickturner, thanks for the kind words. Happy to hear you're finding it useful!

Out of curiousity, does that file have the string `graphql` in it?

It's not a limitation of Webpack but rather the current design of the Relay Compiler as was ported over to this codebase. It scans for files with `graphql` in it and tries to compile those files.

This can definitely be improved and I'll leave this issue open as a reminder to eventually have a deeper integration with Webpack and its loader system, but as a short term fix, can tweak the logic in this file - https://github.com/thusfresh/relay-compiler-webpack-plugin/blob/master/src/getFileFilter.js

**Comment by coleturner** [comment]
The file that's attributed to `ERROR in ./app/assets/stylesheets/main.scss` does not contain a `graphql` template literal however the file that's actually causing it does (Feed.js)

**Comment by tazsingh** [comment]
Thanks @colepatrickturner, sorry for the delay (been a bit busy on my end).

To confirm, the `.scss` file doesn't even contain the string `graphql`? Not even a template literal, but just the string?

Can you provide me with replication steps for this? A repo that replicates this issue would be ideal. If it's too much, a Webpack config and a basic JS example can work too.

**Comment by coleturner** [comment]
That's correct regarding the file name, no `graphql` literals in the CSS file. `main.scss` is the last file in my entry point array.

I unfortunately don't have steps or a repo (yet) to replicate this, but if I come across one I will come back to this issue. Thanks for your time!
