### ISSUE TITLE
Out of order compilation causing "module not found" error

### ISSUE THREAD

**Issue by sj26** [thusfresh/relay-compiler-webpack-plugin#4]
We are in the progress of migrating to relay modern. We're currently running a relay classic environment and just starting to convert to relay compat. I have a parent relay classic container which requires a child compat fragment container. The parent does a getFragment on the child. (https://github.com/buildkite/frontend/pull/280)

If I run the relay compiler normally the webpack build works great! If I remove the generated files and again run a webpack build expecting the plugin to generate the graphql files instead then I get an error like:

```
yarn run v0.24.6
$ NODE_ENV=development webpack --config webpack/config.js --progress --bail
 62% building modules 903/1029 modules 126 active ...core-js/library/fn/symbol/iterator.jsModuleNotFoundError: Module not found: Error: Can't resolve './__generated__/AgentTokens_organization.graphql' in '.../app/components/agent/Index'
    at factoryCallback (.../node_modules/webpack/lib/Compilation.js:260:39)
    at factory (.../node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    ...
    at resolver.doResolve.createInnerCallback (.../node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
resolve './__generated__/AgentTokens_organization.graphql' in '.../app/components/agent/Index'
  using description file: .../package.json (relative path: ./app/components/agent/Index)
  after using description file: .../package.json (relative path: ./app/components/agent/Index)
    using description file: .../package.json (relative path: ./app/components/agent/Index/__generated__/AgentTokens_organization.graphql)
      as directory
        .../app/components/agent/Index/__generated__/AgentTokens_organization.graphql doesn't exist
      no extension
        .../app/components/agent/Index/__generated__/AgentTokens_organization.graphql doesn't exist
      .js
        .../app/components/agent/Index/__generated__/AgentTokens_organization.graphql.js doesn't exist
      .json
        .../app/components/agent/Index/__generated__/AgentTokens_organization.graphql.json doesn't exist
```

I found that changing the `after-compile` to a `before-compile` in the plugin fixes the issue. Should that perhaps be a before instead of an after?

**Comment by tazsingh** [comment]
It's currently in the `after-compile` as the compiler has to run on the built files from Webpack. However this was more of a forward looking decision once we have a tighter integration within Webpack itself as we need to change a few of `relay-compiler`'s APIs to make this happen. Even then, we'll have to change it to be part of the `make` phase to build directly within Webpack.

If having it in the `before-compile` works right now, happy to make that change to accommodate until we have that tighter integration. 👍

**Comment by sj26** [comment]
Nice, thanks!

Yeah, we're also having trouble because the relay compiler seems to have a hard dependency on watchman which is a bummer for CI. If there were a more isolated way to generate the dependency using webpack and a per file transform then that'd be ideal. 👌 But I can see that requires some rework of the compiler codebase.

**Comment by tazsingh** [comment]
Exactly :) And having errors reported within the Compiler that lives outside of Webpack (where all other build errors are reported) is a pain as well.

Keep an eye on this repo as now that Relay Modern has been officially released and therefore its APIs aren't undergoing as much change, those deeper change will be coming in future releases.

**Comment by sj26** [comment]
Hooray!
