### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by PaulLeCam** [thusfresh/relay-compiler-webpack-plugin#8]
Hello,

As we don't currently have any project using this plugin at Mainframe, we haven't been able to maintain it as it should.
Consequently, we're willing to transfer this repository and the npm access to publish new versions to whoever wants to continue supporting it.

@danielholmes your fork seems the most up-to-date, would you be interested in getting this repo transferred to your account and added to npm?

Thanks.

**Comment by danielholmes** [comment]
@PaulLeCam Yes I would

**Comment by PaulLeCam** [comment]
Great!
What is you npm username please?

@howleysv can you make the transfer when possible please?

**Comment by howleysv** [comment]
@danielholmes I've added you as owner to https://www.npmjs.com/package/relay-compiler-webpack-plugin

**Comment by PaulLeCam** [comment]
@howleysv shouldn't we also transfer the GitHub repo so the existing links would get redirected rather than continue to point here?

**Comment by howleysv** [comment]
Which links are you thinking about?

**Comment by PaulLeCam** [comment]
Existing links to `thusfresh/relay-compiler-webpack-plugin`, notably from https://www.npmjs.com/package/relay-compiler-webpack-plugin
Basically making sure @danielholmes owns the canonical repository rather than only his fork.

**Comment by howleysv** [comment]
As far as I can tell, pushing a new release to npm will rewrite all this metadata based on what is in `package.json`. So I don't think there's anything more to do, but I'm not an npm pro 😄 

Regarding github, I don't think there's a need to do anything either. I don't think you can transfer a repo to an account that is already maintaining a fork of the same name. I've seen plenty of "canonical" repos on github that say "forked from ...". But happy to do whatever you want here @danielholmes

**Comment by danielholmes** [comment]
@howleysv On the npm side of things I have the same assumptions as you, but maybe that's because I'm no pro either 😄  - I'll be in touch if I find any issues.

As for the github repo, I think it works best if you put a message and link at the top of the README saying it's no longer maintained, then once that is done archive the repo. I'll send a PR for the README change.
